### ISSUE TITLE
Server Crash when creating ore sheep

### ISSUE THREAD

**Issue by CrowBBGN** [Icedice9/OreSheep#6]
Tried making an ore sheep. Splashed it and tried to feed it a diamond and crash. 

Crash report:
https://hastebin.com/jejolivita.sql

**Comment by mattcloward** [comment]
Thanks for the report! I'll try to get a fix out by the end of the week!

**Comment by mattcloward** [comment]
Okay, I found the bug. It's a little more difficult to fix than I originally thought, so I might have to push the fix to next week. Sorry for the inconvenience!

**Comment by CrowBBGN** [comment]
Any update of the fix? Thanks

**Comment by mattcloward** [comment]
Sorry for the wait! College has kept me busy! The bug has to do with the way the quark blocks do pick block. I want to get out a more permanent fix, but if it comes to it, I might just have to blacklist it. I'll have a fix out either way by the end of the weekend.

**Comment by mattcloward** [comment]
I know I promised to get this fixed this weekend, but even a blacklist isn't as simple as I had hoped. I'll try again this coming week. Thanks for your patience!

**Comment by mattcloward** [comment]
Finally got it fixed! Quark makes ore sheep eat all item blocks on the ground (because they are all breeding items), so be sure to turn off that automatic setting, otherwise when you shear a sheep, it will go into love mode without dropping anything!
