### ISSUE TITLE
ore clash 1.7.10

### ISSUE THREAD

**Issue by TmanDelport** [Icedice9/OreSheep#7]
Hi there, thank you for such an awesome mod, its my most used one. im hopping you can help me, im currently experiencing an ore clash of sorts. when a sheep eats a rutile ore from advanced rocketry it grows cinibar from thaumcraft, and this is the same with iridium ore which then grows fire stone ore. i dont know anything about coding so i cant seem to solve this. any ideas how i could narrow down a cause so i can hopefully fix it? Thanx in advance

**Comment by mattcloward** [comment]
Hello TmanDelport! I'm so happy you're enjoying the mod! I'm looking into your bug report now. What versions of the mods mentioned are you using? I'm trying to get a build put together to test it.

**Comment by TmanDelport** [comment]
Thanx for such a speedy reply. Advanced Rocketry version 1.4.0-15 for minecraft 1.7.10, lip vulpes 0.2.8-33 and thaumcraft 4.2.3.5 and then i have the latest versian of ore sheep. Thanx so much for the help, with your ore sheep i dont have to destroy my beautiful landscape to get ores lol, just one and i set up a system to farm the ores automaticlly :D 

Oh and welcome back from you mission, hope it went well.

Thanx in Advance

**Comment by mattcloward** [comment]
It's so cool that you've found your own style while playing my mod! That was what I was hoping people would do.
This should be more simple than it is, but I can't seem to get Thaumcraft to run correctly. I've manually downloaded the version of Baubles it required, but I get a crash after a few seconds of the game running. How did you get past this/set up your modpack?
Thanks for working with me on this. I'll try to get a fix sometime within next week!

**Comment by TmanDelport** [comment]
I just ran some tests with just the ore sheep mod, Thaumcratft and baubles and it turned on smoothly, the only time my thaumcraft ever causes a crash is when an addon clashes. so maybe try with those 3 mods alone, if they work add advanced Rocketry amd Lip Vulpes back and see if that works. also double check all are for version 1.7.10

**Comment by mattcloward** [comment]
I've been a lot more busy this week than I had hoped. I'll try to get a fix out next week.

**Comment by TmanDelport** [comment]
No problem. where u able to solve the crash problem? and i dont mind waiting, aside from that the mod is still perfect :D Thanx again for helping.

**Comment by mattcloward** [comment]
Just barely put out a release that should fix the issue. The problem was that advanced rocketry ore metadata is weird and my mod wasn't reading it correctly. Let me know if it works!

**Comment by TmanDelport** [comment]
Just tested it now and works absolutely perfectly thank you so much :D i cant thank you enough :D 
before i close this though i wanted to ask you one more quick question, the rf tools mod adds one ore, its called the dimensional shard ore, how would i go about making it growable on the sheep, i havent been able to figure out the config files even using the vid tutorials, lol. if it isnt possible its not a problem, was just curious.

Thanks again.

**Comment by mattcloward** [comment]
Great question! It depends on the block, but most blocks work. 
First you need to know the unlocalized name for your block. If I'm seeing this right, I think the one you are looking for is "dimensionalShardBlock" 
Next, you need to navigate to the "OreConfig.txt" file. This is found in your .minecraft folder in \.minecraft\config\oresheep. 
Open the file (with a text editor like Notepad++ where each block is on its own line) and paste the name of the block on a new line above the line that says "blocks to eat:" 
Finally, log out of any worlds you are on and log back in. 
The sheep should be able to eat that block! 
Let me know if any part of that is confusing! I'm planning on doing a better video in the future to make it easier to understand.

**Comment by TmanDelport** [comment]
Tested it now and it worked perfectly! Thank you so much :D your mod is by far one of the most amazing and useful mods out there, thank you so much. I cant thank you enough for all your help, if there is ever anything i can do to Thank you just let me know. 

ps in a few years if iv made my server id love your you to join in to see all that iv been building.

Thanks again, sincerly Tommy Lee Delport
