### ISSUE TITLE
Oresheep wont eat an ore after using the potion and diamond to transform them

### ISSUE THREAD

**Issue by kpkirsch** [Icedice9/OreSheep#9]
Did the process to create an ore sheep on top of a diamond ore. It went from sheep to ore sheep but never ate the ore, waited ~10 minutes, went into creative and turned it into a diamond sheep with an ore block. After shearing it, it wont eat anything. Just makes the animation. Stands on top of diamond ore, cobblestone and smooth stone blocks. Can breed with stone still and baby was diamond sheep but after it was sheared it didnt regrow as well. If given an ore in creative they wont regen the ore while standing on stone/ore just making the eating animation.

Oresheep log: (v3.1.0 on 1.7.10 same modpack as previous issue but not same server)
[Log.txt](https://github.com/Icedice9/OreSheep/files/2300047/Log.txt)

[latest.log](https://github.com/Icedice9/OreSheep/files/2300048/latest.log)
[fml-client-latest.log](https://github.com/Icedice9/OreSheep/files/2300049/fml-client-latest.log)

**Comment by mattcloward** [comment]
Do you have th game rule of “doMobGriefing” set to false? If so, it must be set to true, otherwise they can’t break blocks. In 1.12, you can do the command “/ignoremobgriefing true,” but I haven’t implemented that into 1.7.10.
Let me know if this works!

**Comment by kpkirsch** [comment]
Worked! thanks for the quick response.

**Comment by mattcloward** [comment]
Happy to help. Have fun!
